# Generated by Django 4.1.3 on 2022-11-13 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_task_create_by_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
